# Site Settings
title: Pablo Catalan
email: pablocatalanfdez@gmail.com
theme: jekyll-theme-cayman
description: >
  Living somewhere in the intersection between Math and Biology (if that even exists).
baseurl: ""
url: "http://pablocatalan.github.io"
twitter_username: the100footpole
github_username:  pablocatalan
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
